services:
  - type: web
    name: udon-reservas
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.office365.com
      - key: EMAIL_PORT
        value: 587
